### ISSUE TITLE
Serilog Listener generates an error when hit _logger.Write in SerilogEventListener

### ISSUE THREAD

**Issue by johnkattenhorn** [sceneskope/service-fabric#1]
If we try to use the SerilogEventListener it is detecting the event no problem but fails with the following message after the first message has been sent.

```
FatalExecutionEngineError was detected
Message: The runtime has encountered a fatal error. The address of the error was at 0x24d892c8, on thread 0x4dec. The error code is 0x80131623. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.
```

Any idea what this could be or how to debug it ?

**Comment by nrandell** [comment]
I've no idea on this - any stack trace or context around this?

**Comment by johnkattenhorn** [comment]
No it seems be faulting somewhere inside a unmanaged code component. I've spoken with someone from the SF team who says they have been this before but from the event source itself which doesn't make a lot of sense to me.

They directed me at their new EventFlow but they only takes Serilog as an input I want everything to go to Serilog as an output so that no good for me either.

**Comment by johnkattenhorn** [comment]
In some of my services I can't get the listener to pick up any of the events at all, which is odd but I've had problems with this before.

All I'm really trying to achieve is to pick up the messages from the SF runtime and place in the same place as the Serilog events we raise in code.

**Comment by nrandell** [comment]
Strange - I've not seen this before, but I haven't done any SF work for a few weeks.
However I'm glad someone else is using serilog for service fabric logging - serilog and seq seem to be so much easier than the official mechanism.

**Comment by nrandell** [comment]
Just had a thought. In your ServiceEventSource, are you referencing Microsoft.Diagnostics.Tracing or System.Diagnostics.Tracing

**Comment by nrandell** [comment]
Is this still an issue? I've not seen it on any of my systems.
